#!/system/bin/sh

### BEGIN INIT INFO
# Exec: boot
# Type: permanent
### END INIT INFO

log -p i -t boot "\

  ____ _____  _              _           _     _
 |  _ \_   _|/ \   _ __   __| |_ __ ___ (_) __| |
 | |_) || | / _ \ |  _ \ / _  |  __/ _ \| |/ _  |
 |  _ < | |/ ___ \| | | | (_| | | | (_) | | (_| |
 |_| \_\|_/_/   \_\_| |_|\__,_|_|  \___/|_|\__,_|


  Welcome to (RT)Android `getprop ro.build.version.release`

";

# iszilagyi GPS
chmod 666 /dev/ttyS0
# iszilagyi FTDI
insmod /system/lib/modules/ftdi_sio.ko



